<?php

/**
 * @file
 * Contains pokemon_deck.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pokemon_deck_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pokemon_deck module.
    case 'help.page.pokemon_deck':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Everything related to the decks') . '</p>';
      return $output;

    default:
  }
}
